# -*- coding: utf-8 -*-
"""common

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14NqkVN7n3WkpNRH3DsbBJ04XqZ0mtrcs
"""

import os
import time
import glob
import zipfile
import pandas as pd
import numpy as np
import re
import random
from sklearn.metrics import cohen_kappa_score
from sklearn.model_selection import train_test_split
from google.colab import userdata

# =================配置区域=================
# 🟢 模式选择: "MOCK" / "GEMINI" / "OPENAI"
# 跑全量建议先用 MOCK 测通，再换 GEMINI (免费额度高)
PROVIDER = "MOCK"

# 🟢 API KEY
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY", "YOUR_GEMINI_KEY")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "YOUR_OPENAI_KEY")

MODEL_NAME = "gemini-2.0-flash"
# =========================================

# --- 1. API 初始化 ---
if PROVIDER == "GEMINI":
    import google.generativeai as genai
    try: genai.configure(api_key=GOOGLE_API_KEY)
    except: pass
elif PROVIDER == "OPENAI":
    from openai import OpenAI
    try: openai_client = OpenAI(api_key=OPENAI_API_KEY)
    except: pass

# --- 2. LLM 调用函数 ---
def call_llm(prompt_text, max_tokens=200, temperature=0.0):
    text_out, tokens_in = "", 0
    try:
        if PROVIDER == "MOCK":
            time.sleep(0.001) # 全量Mock时为了速度，延迟设极低
            if "Essay A" in prompt_text: text_out = random.choice(["Essay A", "Essay B"])
            elif "Development:" in prompt_text:
                d, o, l = random.randint(3,6), random.randint(3,6), random.randint(2,5)
                text_out = f"Development: {d}\nOrganization: {o}\nLanguage: {l}"
            else: text_out = str(random.randint(1, 6))
            tokens_in = len(prompt_text) // 4 # 粗略模拟Token数

        elif PROVIDER == "GEMINI":
            safety = [{"category": c, "threshold": "BLOCK_NONE"} for c in ["HARM_CATEGORY_HARASSMENT", "HARM_CATEGORY_HATE_SPEECH", "HARM_CATEGORY_SEXUALLY_EXPLICIT", "HARM_CATEGORY_DANGEROUS_CONTENT"]]
            model = genai.GenerativeModel(MODEL_NAME, safety_settings=safety, generation_config={"temperature": temperature, "max_output_tokens": max_tokens})
            resp = model.generate_content(prompt_text)
            if resp.candidates:
                text_out = resp.text.strip()
                try: tokens_in = resp.usage_metadata.prompt_token_count
                except: pass

        elif PROVIDER == "OPENAI":
            resp = openai_client.chat.completions.create(model=MODEL_NAME, messages=[{"role": "user", "content": prompt_text}], temperature=temperature, max_tokens=max_tokens)
            text_out = resp.choices[0].message.content.strip()
            tokens_in = resp.usage.prompt_tokens

    except Exception as e:
        print(f"❌ API Error: {e}")
        if "429" in str(e): time.sleep(10)
    return text_out, tokens_in

# --- 3. 数据加载 ---
def load_data():
    if not os.path.exists('ASAP_2.0'): os.system('git clone https://github.com/scrosseye/ASAP_2.0.git')
    EXTRACT_PATH = 'ASAP_2.0/'
    csv_files = glob.glob(f"{EXTRACT_PATH}/*train*.csv")
    if not csv_files:
        zips = glob.glob("ASAP_2.0/*train.zip")
        if zips:
            with zipfile.ZipFile(zips[0], 'r') as zip_ref: zip_ref.extractall(EXTRACT_PATH)
            csv_files = glob.glob(f"{EXTRACT_PATH}/*train*.csv")
    if not csv_files:
        # Mock兜底
        return pd.DataFrame({'essay_id': range(20), 'full_text': ["Full length essay text "*50]*20, 'score': [3]*20})
    full_df = pd.read_csv(csv_files[0])
    score_col = 'score' if 'score' in full_df.columns else 'domain1_score'
    return full_df.dropna(subset=[score_col])

FULL_DF = load_data()
essay_col = 'full_text' if 'full_text' in FULL_DF.columns else 'essay'
score_col = 'score' if 'score' in FULL_DF.columns else 'domain1_score'
id_col = 'essay_id'

train_df, test_df = train_test_split(FULL_DF, test_size=0.2, random_state=42)

# 🔥🔥🔥 关键修改：跑全量 Test 集 🔥🔥🔥
target_df = test_df.copy()
print(f"📊 数据就绪: 评测全量测试集 N={len(target_df)}")

# --- 4. Few-Shot 构建 (无截断版) ---
def build_few_shot(training_data):
    shots = []
    if len(training_data) < 10: return "Mock Examples"
    for score in range(1, 7):
        cand = training_data[training_data[score_col] == score]
        if not cand.empty:
            # 🔥🔥🔥 关键修改：移除 [:600] 截断，使用完整文本 🔥🔥🔥
            full_txt = str(cand.iloc[0][essay_col])
            shots.append(f"\n---\n[Example Score {score}]\n{full_txt}\n---")
    return "".join(shots)

FEW_SHOT_CONTEXT = build_few_shot(train_df)

# --- 5. 完整官方 Rubric ---
HOLISTIC_RUBRIC_FULL = """
SCORE OF 6: An essay in this category demonstrates clear and consistent mastery, although it may have a few minor errors. A typical essay effectively and insightfully develops a point of view on the issue and demonstrates outstanding critical thinking; the essay uses clearly appropriate examples, reasons, and other evidence taken from the source text(s) to support its position; the essay is well organized and clearly focused, demonstrating clear coherence and smooth progression of ideas; the essay exhibits skillful use of language, using a varied, accurate, and apt vocabulary and demonstrates meaningful variety in sentence structure; the essay is free of most errors in grammar, usage, and mechanics.

SCORE OF 5: An essay in this category demonstrates reasonably consistent mastery, although it will have occasional errors or lapses in quality. A typical essay effectively develops a point of view on the issue and demonstrates strong critical thinking; the essay generally using appropriate examples, reasons, and other evidence taken from the source text(s) to support its position; the essay is well organized and focused, demonstrating coherence and progression of ideas; the essay exhibits facility in the use of language, using appropriate vocabulary demonstrates variety in sentence structure; the essay is generally free of most errors in grammar, usage, and mechanics.

SCORE OF 4: An essay in this category demonstrates adequate mastery, although it will have lapses in quality. A typical essay develops a point of view on the issue and demonstrates competent critical thinking; the essay using adequate examples, reasons, and other evidence taken from the source text(s) to support its position; the essay is generally organized and focused, demonstrating some coherence and progression of ideas exhibits adequate; the essay may demonstrate inconsistent facility in the use of language, using generally appropriate vocabulary demonstrates some variety in sentence structure; the essay may have some errors in grammar, usage, and mechanics.

SCORE OF 3: An essay in this category demonstrates developing mastery, and is marked by ONE OR MORE of the following weaknesses: develops a point of view on the issue, demonstrating some critical thinking, but may do so inconsistently or use inadequate examples, reasons, or other evidence taken from the source texts to support its position; the essay is limited in its organization or focus, or may demonstrate some lapses in coherence or progression of ideas displays; the essay may demonstrate facility in the use of language, but sometimes uses weak vocabulary or inappropriate word choice and/or lacks variety or demonstrates problems in sentence structure; the essay may contain an accumulation of errors in grammar, usage, and mechanics.

SCORE OF 2: An essay in this category demonstrates little mastery, and is flawed by ONE OR MORE of the following weaknesses: develops a point of view on the issue that is vague or seriously limited, and demonstrates weak critical thinking; the essay provides inappropriate or insufficient examples, reasons, or other evidence taken from the source text to support its position; the essay is poorly organized and/or focused, or demonstrates serious problems with coherence or progression of ideas; the essay displays very little facility in the use of language, using very limited vocabulary or incorrect word choice and/or demonstrates frequent problems in sentence structure; the essay contains errors in grammar, usage, and mechanics so serious that meaning is somewhat obscured.

SCORE OF 1: An essay in this category demonstrates very little or no mastery, and is severely flawed by ONE OR MORE of the following weaknesses: develops no viable point of view on the issue, or provides little or no evidence to support its position; the essay is disorganized or unfocused, resulting in a disjointed or incoherent essay; the essay displays fundamental errors in vocabulary and/or demonstrates severe flaws in sentence structure; the essay contains pervasive errors in grammar, usage, or mechanics that persistently interfere with meaning.
"""

# --- 6. 保存函数 ---
def save_results(results, name):
    df = pd.DataFrame(results)
    valid = df.dropna(subset=['pred_score'])
    if valid.empty: return print(f"❌ {name}: No Valid Results")
    valid['pred_score'] = valid['pred_score'].astype(int)
    valid['human_score'] = valid['human_score'].astype(int)
    qwk = cohen_kappa_score(valid['human_score'], valid['pred_score'], weights='quadratic')

    ts = time.strftime('%Y%m%d_%H%M%S')
    prefix = "MOCK_" if PROVIDER == "MOCK" else ""
    csv_f = f"{prefix}{name}_Data_{ts}.csv"
    txt_f = f"{prefix}{name}_Report_{ts}.txt"
    df.to_csv(csv_f, index=False)

    extra = ""
    if 'score_dev' in valid.columns:
        c_d = valid['score_dev'].corr(valid['human_score'])
        c_o = valid['score_org'].corr(valid['human_score'])
        c_l = valid['score_lang'].corr(valid['human_score'])
        extra = f"\nTraits Corr: D={c_d:.2f}, O={c_o:.2f}, L={c_l:.2f}"

    report = f"=== {name} ===\nMode: {PROVIDER}\nData Size: {len(valid)}\nQWK: {qwk:.4f}{extra}\nSaved: {csv_f}"
    with open(txt_f, "w") as f: f.write(report)
    print(report)