# -*- coding: utf-8 -*-
"""run_baseline1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l-39vUwo1YR1edVH6yBA_rt0X8jOs6ty
"""

import re
import time
from common import (
    target_df, essay_col, score_col, id_col,
    call_llm, save_results, FEW_SHOT_CONTEXT, PROVIDER,
    HOLISTIC_RUBRIC_FULL
)

def run():
    print(f"\n🚀 Starting Baseline 1 (Full Context, {len(target_df)} essays)...")
    results = []

    for idx, row in target_df.iterrows():
        # 🔥 Prompt: 包含完整 Rubric, 完整 Few-Shot, 完整当前作文
        prompt = f"""System: You are an expert essay scorer for ASAP 2.0.

### OFFICIAL RUBRIC
{HOLISTIC_RUBRIC_FULL}

### REFERENCE EXAMPLES
{FEW_SHOT_CONTEXT}

### TARGET ESSAY
{row[essay_col]}

### TASK
Based on the Rubric and Examples above, assign a holistic score (1-6).
Output ONLY the integer."""

        start_t = time.time()
        raw_out, in_tok = call_llm(prompt, max_tokens=50)
        latency = time.time() - start_t

        try:
            pred = int(re.findall(r'\d+', raw_out)[0])
            pred = max(1, min(6, pred))
        except:
            pred = None

        results.append({
            'essay_id': row[id_col], 'human_score': row[score_col],
            'pred_score': pred, 'input_tokens': in_tok,
            'latency': round(latency, 2), 'raw_output': raw_out
        })

        # 进度打印
        if (idx+1) % 10 == 0:
            print(f"Processed {idx+1}/{len(target_df)}...")
        if PROVIDER != "MOCK": time.sleep(1)

    save_results(results, "Baseline1_Holistic_FullContext")

if __name__ == "__main__":
    run()